// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
// Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication

/*
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 */

/*
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 * Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication Such comment much duplication
 */

function justForFun() {
  var $suchClass = $(".suchClass");

  $suchClass.trigger("click");
  $suchClass.trigger("click");
  $suchClass.trigger("click");
  $suchClass.trigger("click");
  $suchClass.trigger("click");

  console.log("Some random print");

  $suchClass.trigger("click");
  $suchClass.trigger("click");
  $suchClass.trigger("click");
  $suchClass.trigger("click");
  $suchClass.trigger("click");
  $suchClass.trigger("click");
}
