version: 2.1

orbs:
  codacy: codacy/base@12.1.1
  codacy_plugins_test: codacy/plugins-test@2.0.11

jobs:
  test:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Test
          command: scripts/test.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "scalafmt::test;
                 test:scalafmt::test;
                 sbt:scalafmt::test;
                 Test / compile;
                 stage"
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: test
          cmd: sbt test
          requires:
            - publish_docker_local
      - codacy_plugins_test/run:
          name: plugins_test
          run_json_tests: false
          run_duplication_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - test
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
           name: tag_version
           context: CodacyAWS
           requires:
             - codacy/publish_docker
